# don't build tags, it's redundant
if: tag IS blank
language: node_js
node_js:
  - 12
script:
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - echo $APPLITOOLS_BATCH_ID
  - cd tutorial-cypress
  - npm install
  - npx eyes-setup
  - npx cypress run --spec "cypress/integration/examples/actions.spec.js"
